### ISSUE TITLE
Metatogger flaged as malware

### ISSUE THREAD

**Issue by eitancaspi** [luminescence-software/Metatogger-Support#2]
![2024-06-01 16_24_55-Notification - ESET NOD32 Antivirus](https://github.com/luminescence-software/Metatogger-Support/assets/7686315/531fd904-1e5d-4256-a80b-c11097597634)
![2024-06-01 16_31_11-Downloads](https://github.com/luminescence-software/Metatogger-Support/assets/7686315/de149403-2676-4dc7-a525-c51c727e993d)

**Comment by eitancaspi** [comment]
Hello,

I downloaded https://www.luminescence-software.org/download/metatogger/Metatogger-Installer.exe and when I tried to run it - my ESET NOD32 blocked the run, twice, each time with different warnings.

See attached and also the following links.

https://metatogger.en.lo4d.com/virus-malware-tests

https://www.virustotal.com/gui/file/bc412fc0b379e9c443eea2cc30b2a9b30bb2f5ac818ee0efa32a7eba3e0afb04/detection/f-bc412fc0b379e9c443eea2cc30b2a9b30bb2f5ac818ee0efa32a7eba3e0afb04-1714014630

How to ask ESET to clear this
https://support.eset.com/en/kb141-submit-a-virus-website-or-potential-false-positive-sample-to-the-eset-lab#SubmitFile

**Comment by CyberSinh** [comment]
Hello,

Since Metatogger is no longer [electronically signed](https://www.luminescence-software.org/en/metatogger/news#metatogger-binaries-will-), some antivirus programs (often the least powerful) consider it suspicious and block it.

These are [false alerts](https://www.luminescence-software.org/en/metatogger/documentation#a-windows-smartscreen-ale) that users can safely ignore.

I'm surprised that Eset NOD32 blocks Metatogger, as this antivirus does indeed consider Metatogger healthy on [VirusTotal](https://www.virustotal.com/gui/url/a20e85efd6410f0c0b5256d90ab8a855399f6605c49d5e96d7a7f1b85ad8f40a).

Unfortunately, I can't contact these antivirus publishers every time I release an update to inform them of the false positive.
